chapter {* Generated by Lem from \<open>lem/rlplem.lem\<close>. *}

theory "RlplemAuxiliary" 

imports
  Main
  "LEM.Lem_pervasives"
  "LEM.Lem_word"
  "Word256"
  "Word160"
  "Word8"
  "Keccak"
  "Rlplem"

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination BE_rev_prim by lexicographic_order

termination BE_rev by lexicographic_order

termination BD_rev by lexicographic_order

termination RLP by lexicographic_order


(****************************************************)
(*                                                  *)
(* Lemmata                                          *)
(*                                                  *)
(****************************************************)

lemma word_rsplit160_def_lemma:
" ((\<forall> w. (word_rsplit_aux (to_bl w) (( 20 :: nat))) = word_rsplit w)) "
(* Theorem: word_rsplit160_def_lemma*)(* try *) by auto



end
